Added a function blacklist which will invalidate the old token and du…
LJOSC/checkmark-backend pull request #45
Opened 2024-07-17 18:27 UTC by het4399

…ring refresh access token a new refresh token will create.

This pr closes #27 .Let me know if there is any changes in it

2024-07-20 14:16 UTC, HarshDobariya79 requested changes
Thank you for the PR @het4399. A few changes I've requested.

Can you please also modify the **verifyRefreshToken** middleware to take the token from the body (without Bearer text) instead of the authorization header?
https://github.com/LJOSC/checkmark-backend/blob/a7e1084391261b6c376f393115810c5bd3f4f3c2/src/middlewares/verifyRefreshToken.ts#L28-L72

Also can you please add one validation as well to make sure we only allow the requests with the refreshToken in the request body, and add that middleware before verifyRefreshToken middleware in the route?
https://github.com/LJOSC/checkmark-backend/blob/a7e1084391261b6c376f393115810c5bd3f4f3c2/src/routes/user/user.validation.ts#L38-L42

2024-07-20 14:16 UTC, HarshDobariya79 commented on src/routes/user/user.dao.ts
> +};
There's already one function present in the same file named `logoutUser` which is doing the same work. Can you please rename that to `blacklistToken` and use that? Be sure to rename wherever it is used as well.

Also don't add try catch blocks in the dao since we're already having them inside service.

2024-07-22 19:06 UTC, het4399 commented
> checkmark-backend@1.0.0 format
> prettier --write 'src/**/*.{js,ts,tsx,json,md}'

src/configs/envVars.ts 378ms (unchanged)
src/configs/logger.ts 27ms (unchanged)
src/cron/filterBlacklistedTokens.ts 25ms (unchanged)
src/cron/index.ts 5ms (unchanged)
src/index.ts 33ms (unchanged)
src/middlewares/verifyAccessToken.ts 46ms (unchanged)
src/middlewares/verifyRefreshToken.ts 34ms (unchanged)
src/routes/index.ts 28ms (unchanged)
src/routes/user/user.controller.ts 102ms (unchanged)
src/routes/user/user.dao.ts 63ms (unchanged)
src/routes/user/user.routes.ts 16ms (unchanged)
src/routes/user/user.service.ts 99ms (unchanged)
src/routes/user/user.types.ts 5ms (unchanged)
src/routes/user/user.validation.ts 37ms (unchanged)
src/services/db.ts 18ms (unchanged)
src/services/mailing.ts 16ms (unchanged)
src/types/auth.ts 2ms (unchanged)
src/types/express.d.ts 7ms (unchanged)
src/utils/APIError.ts 16ms (unchanged)
src/utils/errors.ts 44ms (unchanged)
src/utils/format.ts 19ms (unchanged)
src/utils/generateToken.ts 34ms (unchanged)
src/utils/handleMongoError.ts 11ms (unchanged)
src/utils/http-status.ts 5ms (unchanged)
src/utils/HttpException.ts 14ms (unchanged)
src/utils/logger.ts 30ms (unchanged)
src/utils/responseMessages.ts 2ms (unchanged)

> checkmark-backend@1.0.0 lint:fix
> eslint 'src/**/*.{js,ts,tsx}' --fix


Oops! Something went wrong! :(

ESLint: 8.57.0

No files matching the pattern "'src/**/*.{js,ts,tsx}'" were found.
Please check for typing mistakes in the pattern.

husky - pre-commit script failed (code 2)

I am not able to commit the code,i was not able to fix this issue of eslint

can you help me out ?

2024-07-23 12:56 UTC, HarshDobariya79 commented
> > checkmark-backend@1.0.0 format
> > prettier --write 'src/**/*.{js,ts,tsx,json,md}'
> 
> src/configs/envVars.ts 378ms (unchanged) src/configs/logger.ts 27ms (unchanged) src/cron/filterBlacklistedTokens.ts 25ms (unchanged) src/cron/index.ts 5ms (unchanged) src/index.ts 33ms (unchanged) src/middlewares/verifyAccessToken.ts 46ms (unchanged) src/middlewares/verifyRefreshToken.ts 34ms (unchanged) src/routes/index.ts 28ms (unchanged) src/routes/user/user.controller.ts 102ms (unchanged) src/routes/user/user.dao.ts 63ms (unchanged) src/routes/user/user.routes.ts 16ms (unchanged) src/routes/user/user.service.ts 99ms (unchanged) src/routes/user/user.types.ts 5ms (unchanged) src/routes/user/user.validation.ts 37ms (unchanged) src/services/db.ts 18ms (unchanged) src/services/mailing.ts 16ms (unchanged) src/types/auth.ts 2ms (unchanged) src/types/express.d.ts 7ms (unchanged) src/utils/APIError.ts 16ms (unchanged) src/utils/errors.ts 44ms (unchanged) src/utils/format.ts 19ms (unchanged) src/utils/generateToken.ts 34ms (unchanged) src/utils/handleMongoError.ts 11ms (unchanged) src/utils/http-status.ts 5ms (unchanged) src/utils/HttpException.ts 14ms (unchanged) src/utils/logger.ts 30ms (unchanged) src/utils/responseMessages.ts 2ms (unchanged)
> 
> > checkmark-backend@1.0.0 lint:fix
> > eslint 'src/**/*.{js,ts,tsx}' --fix
> 
> Oops! Something went wrong! :(
> 
> ESLint: 8.57.0
> 
> No files matching the pattern "'src/**/*.{js,ts,tsx}'" were found. Please check for typing mistakes in the pattern.
> 
> husky - pre-commit script failed (code 2)
> 
> I am not able to commit the code,i was not able to fix this issue of eslint
> 
> can you help me out ?

Can you confirm the directory name from which you're committing?

2024-07-24 06:22 UTC, het4399 commented
> > > checkmark-backend@1.0.0 format
> > > prettier --write 'src/**/*.{js,ts,tsx,json,md}'
> > 
> > 
> > src/configs/envVars.ts 378ms (unchanged) src/configs/logger.ts 27ms (unchanged) src/cron/filterBlacklistedTokens.ts 25ms (unchanged) src/cron/index.ts 5ms (unchanged) src/index.ts 33ms (unchanged) src/middlewares/verifyAccessToken.ts 46ms (unchanged) src/middlewares/verifyRefreshToken.ts 34ms (unchanged) src/routes/index.ts 28ms (unchanged) src/routes/user/user.controller.ts 102ms (unchanged) src/routes/user/user.dao.ts 63ms (unchanged) src/routes/user/user.routes.ts 16ms (unchanged) src/routes/user/user.service.ts 99ms (unchanged) src/routes/user/user.types.ts 5ms (unchanged) src/routes/user/user.validation.ts 37ms (unchanged) src/services/db.ts 18ms (unchanged) src/services/mailing.ts 16ms (unchanged) src/types/auth.ts 2ms (unchanged) src/types/express.d.ts 7ms (unchanged) src/utils/APIError.ts 16ms (unchanged) src/utils/errors.ts 44ms (unchanged) src/utils/format.ts 19ms (unchanged) src/utils/generateToken.ts 34ms (unchanged) src/utils/handleMongoError.ts 11ms (unchanged) src/utils/http-status.ts 5ms (unchanged) src/utils/HttpException.ts 14ms (unchanged) src/utils/logger.ts 30ms (unchanged) src/utils/responseMessages.ts 2ms (unchanged)
> > > checkmark-backend@1.0.0 lint:fix
> > > eslint 'src/**/*.{js,ts,tsx}' --fix
> > 
> > 
> > Oops! Something went wrong! :(
> > ESLint: 8.57.0
> > No files matching the pattern "'src/**/*.{js,ts,tsx}'" were found. Please check for typing mistakes in the pattern.
> > husky - pre-commit script failed (code 2)
> > I am not able to commit the code,i was not able to fix this issue of eslint
> > can you help me out ?
> 
> Can you confirm the directory name from which you're committing?

PS F:\Open Source\Project\New\checkmark-backend> ,This is the whole path

2024-07-24 16:35 UTC, HarshDobariya79 commented
> > > > checkmark-backend@1.0.0 format
> > > > prettier --write 'src/**/*.{js,ts,tsx,json,md}'
> > > 
> > > 
> > > src/configs/envVars.ts 378ms (unchanged) src/configs/logger.ts 27ms (unchanged) src/cron/filterBlacklistedTokens.ts 25ms (unchanged) src/cron/index.ts 5ms (unchanged) src/index.ts 33ms (unchanged) src/middlewares/verifyAccessToken.ts 46ms (unchanged) src/middlewares/verifyRefreshToken.ts 34ms (unchanged) src/routes/index.ts 28ms (unchanged) src/routes/user/user.controller.ts 102ms (unchanged) src/routes/user/user.dao.ts 63ms (unchanged) src/routes/user/user.routes.ts 16ms (unchanged) src/routes/user/user.service.ts 99ms (unchanged) src/routes/user/user.types.ts 5ms (unchanged) src/routes/user/user.validation.ts 37ms (unchanged) src/services/db.ts 18ms (unchanged) src/services/mailing.ts 16ms (unchanged) src/types/auth.ts 2ms (unchanged) src/types/express.d.ts 7ms (unchanged) src/utils/APIError.ts 16ms (unchanged) src/utils/errors.ts 44ms (unchanged) src/utils/format.ts 19ms (unchanged) src/utils/generateToken.ts 34ms (unchanged) src/utils/handleMongoError.ts 11ms (unchanged) src/utils/http-status.ts 5ms (unchanged) src/utils/HttpException.ts 14ms (unchanged) src/utils/logger.ts 30ms (unchanged) src/utils/responseMessages.ts 2ms (unchanged)
> > > > checkmark-backend@1.0.0 lint:fix
> > > > eslint 'src/**/*.{js,ts,tsx}' --fix
> > > 
> > > 
> > > Oops! Something went wrong! :(
> > > ESLint: 8.57.0
> > > No files matching the pattern "'src/**/*.{js,ts,tsx}'" were found. Please check for typing mistakes in the pattern.
> > > husky - pre-commit script failed (code 2)
> > > I am not able to commit the code,i was not able to fix this issue of eslint
> > > can you help me out ?
> > 
> > 
> > Can you confirm the directory name from which you're committing?
> 
> PS F:\Open Source\Project\New\checkmark-backend> ,This is the whole path

Not sure. Maybe we can connect later and resolve this. For now add `-n ` flag with the commit command. That'll skip the husky checks. I won't recommend doing it often, but until we resolve this, you can go with this solution.

2024-07-25 04:23 UTC, het4399 commented
> > > > > checkmark-backend@1.0.0 format
> > > > > prettier --write 'src/**/*.{js,ts,tsx,json,md}'
> > > > 
> > > > 
> > > > src/configs/envVars.ts 378ms (unchanged) src/configs/logger.ts 27ms (unchanged) src/cron/filterBlacklistedTokens.ts 25ms (unchanged) src/cron/index.ts 5ms (unchanged) src/index.ts 33ms (unchanged) src/middlewares/verifyAccessToken.ts 46ms (unchanged) src/middlewares/verifyRefreshToken.ts 34ms (unchanged) src/routes/index.ts 28ms (unchanged) src/routes/user/user.controller.ts 102ms (unchanged) src/routes/user/user.dao.ts 63ms (unchanged) src/routes/user/user.routes.ts 16ms (unchanged) src/routes/user/user.service.ts 99ms (unchanged) src/routes/user/user.types.ts 5ms (unchanged) src/routes/user/user.validation.ts 37ms (unchanged) src/services/db.ts 18ms (unchanged) src/services/mailing.ts 16ms (unchanged) src/types/auth.ts 2ms (unchanged) src/types/express.d.ts 7ms (unchanged) src/utils/APIError.ts 16ms (unchanged) src/utils/errors.ts 44ms (unchanged) src/utils/format.ts 19ms (unchanged) src/utils/generateToken.ts 34ms (unchanged) src/utils/handleMongoError.ts 11ms (unchanged) src/utils/http-status.ts 5ms (unchanged) src/utils/HttpException.ts 14ms (unchanged) src/utils/logger.ts 30ms (unchanged) src/utils/responseMessages.ts 2ms (unchanged)
> > > > > checkmark-backend@1.0.0 lint:fix
> > > > > eslint 'src/**/*.{js,ts,tsx}' --fix
> > > > 
> > > > 
> > > > Oops! Something went wrong! :(
> > > > ESLint: 8.57.0
> > > > No files matching the pattern "'src/**/*.{js,ts,tsx}'" were found. Please check for typing mistakes in the pattern.
> > > > husky - pre-commit script failed (code 2)
> > > > I am not able to commit the code,i was not able to fix this issue of eslint
> > > > can you help me out ?
> > > 
> > > 
> > > Can you confirm the directory name from which you're committing?
> > 
> > 
> > PS F:\Open Source\Project\New\checkmark-backend> ,This is the whole path
> 
> Not sure. Maybe we can connect later and resolve this. For now add `-n ` flag with the commit command. That'll skip the husky checks. I won't recommend doing it often, but until we resolve this, you can go with this solution.

Done,I have pushed the code,Can you have look onto that.

2024-07-25 04:42 UTC, HarshDobariya79 approved these changes
Thank you for implementing the required changes, LGTM.

2024-07-25 04:43 UTC, merged