Added A Docker File
LJOSC/checkmark-backend pull request #7
Opened 2024-06-25 19:33 UTC by het4399

2024-06-26 04:27 UTC, het4399 reviewed
Hey guys,Can you have a look over this.

2024-06-27 18:15 UTC, h3110Fr13nd requested changes
I think one must not add any .env files except .env.example which already exists.
So @het4399 can you remove .env.production file.

Moreover since we're using mongodb, maybe add a db service of mongo in compose.yaml. 

Don't hesitate to ask for help. You can contact us on slack if you feel stuck.

2024-06-27 18:30 UTC, HarshDobariya79 commented
> Moreover since we're using mongodb, maybe add a db service of mongo in compose.yaml.

I think we don't need the mongodb service for the production since we're using **Mongo Atlas**. For the development or testing, we might need that. If there is any way to create a mongodb service only for the dev, it'l help.

2024-06-27 18:35 UTC, HarshDobariya79 commented
@het4399 Thank you for this PR. One thing I would like to suggest is to keep only the comments that are strongly needed in the dockerfiles. For the reference you can see the link present in the issue description.

2024-06-29 16:33 UTC, HarshDobariya79 commented on .dockerignore
> +
Can we remove this section?

2024-06-29 16:33 UTC, HarshDobariya79 commented on Dockerfile
> +
Can we omit these lines as well?

2024-06-29 16:34 UTC, HarshDobariya79 commented on Dockerfile
> +FROM node:${NODE_VERSION}-alpine as base
Instead of specifying the argument for the node version, can we hard code it since it is used only once?

2024-06-29 16:38 UTC, HarshDobariya79 commented
@h3110Fr13nd Can you please review this PR and guide @het4399?

2024-06-30 20:42 UTC, h3110Fr13nd commented on README.Docker.md
Since we're using compose. There should be Steps for compose also.

2024-06-30 20:44 UTC, h3110Fr13nd commented on compose.yaml
> +      - 3000:3000
possibly add `env_file: .env.production`  in server. So that it is accesible while building and running the container

2024-06-30 20:53 UTC, h3110Fr13nd commented on Dockerfile
- [ ] Remove ENV (No need to have ENV commands here. As it can be set from compose.yaml)
- [ ] Remove EXPOSE (No need to expose from Dockerfile. As it can has been set in compose already.)
- [ ] Remove USER (No need to have different user `node`. and then twice switching back and forth between user.)

2024-06-30 20:58 UTC, h3110Fr13nd requested changes
- Dockerfile
  - [ ] Remove ENV (No need to have ENV commands here. As it can be set from compose.yaml)
  - [ ] Remove EXPOSE (No need to expose from Dockerfile. As it can has been set in compose already.)
  - [ ] Remove USER (No need to have different user `node`. and then twice switching back and forth between user.)
- compose.yaml
  - [ ] possibly add `env_file: .env.production` in `server` service. So that it is accesible while building and running the container

2024-07-01 16:38 UTC, HarshDobariya79 commented
@het4399 Can you complete this issue before next **Thursday**? Because many people wants to contribute but due to the lack of **dockerfile** for mongodb, there's a setup overhead. By adding a dockerfile to run a mongodb container quickly will reduce the setup overhead and result in better productivity.

2024-07-01 16:54 UTC, het4399 commented
> @het4399 Can you complete this issue before next **Thursday**? Because many people wants to contribute but due to the lack of **dockerfile** for mongodb, there's a setup overhead. By adding a dockerfile to run a mongodb container quickly will reduce the setup overhead and result in better productivity.

I Will complete it by tomorrow eod.

2024-07-02 05:56 UTC, het4399 commented
@HarshDobariya79 @h3110Fr13nd  ,Hey ,i need help, After adding the mongodb ,i am not able to hit my server ,but instance of mongodb is working.Can you help me out

2024-07-02 18:37 UTC, HarshDobariya79 approved these changes
Thank you for this PR @het4399.

2024-07-02 18:49 UTC, HarshDobariya79 approved these changes
Thank you for this PR @het4399.

2024-07-02 18:51 UTC, h3110Fr13nd approved these changes
Looks good to me.
Good work for docker-compose.db.yaml for mongodb setup.

2024-07-02 18:53 UTC, merged